### ISSUE TITLE
Logs can consume entire storage volume

### ISSUE THREAD

**Issue by SamuelDudley** [goodrobots/maverick#734]
As per the maverick dev VM, ArduPilot and PX4 logs can consume all available storage space.
I suggest that we limit the available log storage, or warn the user when a limit has been reached. Perhaps a maverick command can be implemented to clear the logs?

**Comment by fnoop** [comment]
ROS logs fixed in #817, SIT logs being addressed in #814.  There's no real way to stop logs filling up storage other than implementing separate partitions for logging/data which would be very difficult to do in a generic manner across different storage and platforms.
However, #869 is probably the best solution to this in the long term - monitor the storage and alert the user through various means if it starts to fill up.
